baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hello, World!"
theme = "minimal" 


[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
